# --- General ---

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

set -g set-titles on
set -g status-position top

set -g base-index 1
setw -g pane-base-index 1

# --- Keybinds ---

set -g prefix C-Space
set -g history-limit 100000

unbind C-b
bind C-Space send-prefix

unbind r
bind r source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind \"
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# --- Plugins ---

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'

# --- Themes ---

# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark256'

# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @tokyo-night-tmux_theme night
# set -g @tokyo-night-tmux_transparent 1

# set -g @plugin 'fabioluciano/tmux-tokyo-night'
# set -g @theme_left_separator ''
# set -g @theme_right_separator ''
# set -g @theme_transparent_status_bar 'true'
# set -g @theme_transparent_left_separator_inverse ''
# set -g @theme_transparent_right_separator_inverse ''
# set -g @theme_plugins 'datetime'
# set -g @theme_plugin_datetime_format '%a, %d %b %Y, %H:%M'

set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_default_fill 'number'
set -g @catppuccin_window_default_text ' #W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text ' #W'
set -g @catppuccin_status_left_separator  ' '
set -g @catppuccin_status_right_separator ''
set -g @catppuccin_status_right_separator_inverse 'no'
set -g @catppuccin_status_fill 'icon'
set -g @catppuccin_status_connect_separator 'no'
run '~/.tmux/plugins/tmux/catppuccin.tmux'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ''
set -g status-right '#{E:@catppuccin_status_session}'
set -ag status-right '#{E:@catppuccin_status_application}'
set -agF status-right '#{E:@catppuccin_status_cpu}'
set -agF status-right ' #[bg=#{@thm_blue},fg=#{@thm_crust},reverse]#[noreverse]  #[fg=#{@thm_fg},bg=#{@thm_surface_0}] #{l:#{ram_percentage}}#[reverse,fg=#{@thm_crust}]#[noreverse,bg=default]'
set -agF status-right ' #[bg=#{@thm_pink},fg=#{@thm_crust},reverse]#[noreverse]󰃰 #[fg=#{@thm_fg},bg=#{@thm_surface_0}] %a, %d %b %Y %H:%M#[reverse,fg=#{@thm_crust}]#[noreverse,bg=default]'

# --- Plugin Manager ---

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'

# --- Status ---

set -g status-bg 'default'
set -g status-style 'bg=default'

