[preferred]
default=gnome
org.freedesktop.impl.portal.Notification=kde
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.Print=kde
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome

